# Generated by Django 5.2.12 on 2026-03-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_course_students'),
        ('Instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='Courses.course'),
        ),
    ]
