# Generated by Django 5.2.12 on 2026-03-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
